### ISSUE TITLE
License

### ISSUE THREAD

**Issue by aprokop** [zabookey/KHPCG3.0#1]
What is the license of the code?

**Comment by zabookey** [comment]
I'm not sure what you mean by this. I'll consult with Mike Heroux and figure out what needs to be done.

**Comment by aprokop** [comment]
I meant that in order to clone and modify your code one would generally need to know that the license of software allows that. That means if I want to fork and modify the source code to create a fix for something, the license should allow that, or the code must be in public domain.

See more here: https://github.com/blog/1530-choosing-an-open-source-license

**Comment by zabookey** [comment]
Oh! Okay. I presume it should have a license similar to HPCG or Kokkos. I'll get it figured out and added soon. Thanks for bringing this to my attention.

**Comment by zabookey** [comment]
3 Clause BSD. That's what I'm looking for. I'll get this added

**Comment by aprokop** [comment]
Great, thanks!
